### ISSUE TITLE
"IPFS Chromium" branding of builds

### ISSUE THREAD

**Issue by lidel** [little-bear-labs/ipfs-chromium#32]
Some things we've discussed during sync today:
- rename artifacts published at https://github.com/little-bear-labs/ipfs-chromium/releases to all start with `ipfs-chromium..`
- IPFS Icon? ([svg](https://github.com/ipfs-inactive/logo/blob/master/vector/ipfs-logo-vector-ice-text.svg))

**Comment by John-LittleBearLabs** [comment]
The ipfs-client artifacts aren't supposed to be Chromium specific, so I'm a bit reluctant to do it to them.
Renaming all the _other_ artifacts the same would help to make the distinction more clear.
I'm not sure if any of them are name-prefix-sensitive. chrome.exe.pdb might be, since it's supposed to match up with chrome.exe

If we're doing icon we could also rename the program. I found that useful the one time I did it - if I hit super and type in "chrom" multiple options are there, but if I typed in IPFS it would show me "Chromium (+IPFS)" which was the silly name I chose at the time.

**Comment by lidel** [comment]
My intention is to visually distinguish it from the regular chromium somehow, if user already has plain one installed on their system.

Name  "Chromium (+IPFS)"  is good enough imo, just needs distinct icon.

Since the project is chromium + ipfs:

![2023-06-26_15-46](https://github.com/little-bear-labs/ipfs-chromium/assets/157609/73061459-d670-420e-9b1e-7d34934e814c)

maybe this would be enough?

![2023-06-26_15-46d](https://github.com/little-bear-labs/ipfs-chromium/assets/157609/4d0960f0-eae9-4825-8d0e-82282ae2d25f)


@John-LittleBearLabs if you can point me at the place where original assets are, I could create new ones for you.
